# Generated by Django 3.0.4 on 2020-03-13 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ast', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ast', to='Bebek.Assistant')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inspector', to='Bebek.Assistant')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='leader', to='Bebek.Assistant')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KeyIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=20)),
                ('course_id', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('shift', models.IntegerField()),
                ('room', models.IntegerField()),
                ('date', models.DateTimeField(null=True)),
                ('ast_mapping', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Bebek.AssistantMapping')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Bebek.Assistant')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Bebek.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_approved', models.DateTimeField(null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approver', to='Bebek.Assistant')),
                ('ast_after', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ast_after', to='Bebek.Assistant')),
                ('ast_before', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ast_before', to='Bebek.Assistant')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requester', to='Bebek.Assistant')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField()),
                ('comments', models.CharField(default='-', max_length=255)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Bebek.Indicator')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Bebek.Transaction')),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='key_indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Bebek.KeyIndicator'),
        ),
        migrations.AddField(
            model_name='assistantmapping',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Bebek.Semester'),
        ),
    ]
